defaults:
  repo:
    default_branch: main

  tests:
    Ensure repository settings:
      path: repos/{owner}/{repo}
      json:
        visibility: public
        default_branch: main
        license:
          key: gpl-3.0

    Ensure Actions permissions:
      path: repos/{owner}/{repo}/actions/permissions
      json:
        enabled: true
        allowed_actions: all
      hints:
        - Settings >> Actions >> General >> Actions permissions >> Allow all actions and reusable workflows

    Ensure Workflow permissions:
      path: repos/{owner}/{repo}/actions/permissions/workflow
      json:
        default_workflow_permissions: write
        can_approve_pull_request_reviews: false
      hints:
        - Settings >> Actions >> General >> Workflow permissions >> Read and write permissions

    Ensure '<repo.default_branch>' is protected:
      path: repos/{owner}/{repo}/branches/<repo.default_branch>/protection

    Ensure '<repo.default_branch>' protection settings:
      path: repos/{owner}/{repo}/branches/<repo.default_branch>/protection
      json:
        required_status_checks:
          strict: true
          contexts: []
        required_pull_request_reviews:
          dismiss_stale_reviews: false
          require_code_owner_reviews: false
          required_approving_review_count: 0

    Ensure 'CM tag protections' ruleset:
      prerequisites:
        - name: Get 'CM tag protections' ruleset
          path: repos/{owner}/{repo}/rulesets
          match:
            key: name
            value: CM tag protections
          substitute:
            key: cm_tag_protections
            value: id
      path: repos/{owner}/{repo}/rulesets/<cm_tag_protections>
      json:
        enforcement: active
        conditions:
          ref_name:
            include:
              - refs/tags/v*
        rules:
          - type: creation
          - type: update
          - type: deletion
      hints:
        - Settings >> Rules >> Rulesets

    Ensure Dependabot alerts are enabled:
      path: repos/{owner}/{repo}/dependabot/alerts
      hints:
        - Settings >> Code security and analysis >> Dependabot alerts
