name: No-build workflow

on: [push, workflow_dispatch]

jobs:
  # ref-no-build-workflow:
  #   uses: kerrys-learning-lab/.github/.github/workflows/no-build.workflow.yml@main
  #   secrets:
  #     actor_name: ${{ secrets.KERRYS_LEARNING_LAB_ACTOR }}
  #     actor_token: ${{ secrets.KERRYS_LEARNING_LAB_TOKEN }}
  #     actor_email: ${{ secrets.KERRYS_LEARNING_LAB_EMAIL }}
  ref-bump-version:
    uses: kerrys-learning-lab/.github/.github/workflows/.bump-version.yml@main
    secrets:
      actor_name: ${{ secrets.actor_name }}
      actor_token: ${{ secrets.actor_token }}
      actor_email: ${{ secrets.actor_email }}
